language: python

sudo: true

os: linux

python:
    - "2.7"
    - "3.5"

matrix:
  allow_failures:
    - python: "2.6"
    - python: "3.5"

before_install:
  - sudo chmod u+x .travis/*
  - /bin/bash .travis/before_install

script:
  - /bin/bash .travis/build.sh
